# Generated by Django 4.1.7 on 2023-08-07 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horizonAI', '0004_alter_signup_timestamp_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 7, 13, 55, 42, 196402)),
        ),
    ]
